### ISSUE TITLE
Syntax error on Windows machines

### ISSUE THREAD

**Issue by Zejnilovic** [samnissen/watir-screenshot-stitch#39]
Hello, 

on Windows and only on Windows (Linux works for me just fine) there is a syntax error on line 90 of watir-screenshot-stitch.rb

 `return false unless @browser&.name == :firefox`

the & (ampersand) seems to be the problem. When deleted locally, program resumes working.

**Comment by samnissen** [comment]
Hello! So this is because the gem [requires Ruby 2.3 or greater](http://mitrev.net/ruby/2015/11/13/the-operator-in-ruby/), but doesn't tell you it needs it. Sorry about that! 

I'll keep this issue alive to track efforts to document this requirement.

**Comment by Zejnilovic** [comment]
Wouldn't specifiing the ruby version be the thing to do?
https://bundler.io/v1.5/gemfile_ruby.html

**Comment by submitnine** [comment]
#43 - I created an PR to may close this issue. Please be kind with me since it is my first contribution ever.

**Comment by sandeepnagra** [comment]
@samnissen - I think rather than locking our gem to Ruby version 2.3.0 or higher, we can get rid of ampersand and do a nil check on `@browser.name` object before comparing name value.

We have to make sure our gem is compatible with older versions of Ruby too.

**Comment by samnissen** [comment]
@sandeepnagra I would never want to make it my responsibility to support [Ruby versions not supported by Ruby](https://www.ruby-lang.org/en/downloads/branches/), and am thus against supporting 2.2.x old older versions as a matter of policy.

My preferred path would still be the original remit of the issue, to support only 2.3.x+. -- not just because EOL status of old Rubies, but explicitly because of how amazing the `&.` syntax is. Nil protection is one of the worst parts of being a Ruby developer, one of the biggest slowdowns in producing new code IMO, and I think `&.` should be employed liberally Ruby-wide.

All of that said, this is not the hill I will die on -- if after all of this, you still would prefer to make one change to be more inclusive, I am fine with that. I'll leave it with you to have the final word. (And maybe @submitnine, you would like to take on such a change?)

**Comment by submitnine** [comment]
I can understand both sides. To lock the Ruby version will force users to upgrade ruby or stay with an older version of this gem. Also if the ruby association (?) does not support ruby < 2.3 anymore, it might be harder to maintain older versions of the gem by your own.
Personal I would go with @sandeepnagra because the safe-navigator will be used only on two places. But we should test if the application is still compatible with ruby <2.3 even we find an alternative solution about safe-nagivation. If there is much more which prevents the user from using this gem with older ruby versions, than we could stay with >= 2.3 . So another opinion about this topic would be great and I will find (hopefully) an proper way to fullfill this request :)

**Comment by sandeepnagra** [comment]
Nevermind, I did more analysis and found that watir doesn't support Ruby versions lower than 2.3.0 and it is a dependency for our gem so we can also lock our gem to use Ruby versions >=2.3.0

**Comment by samnissen** [comment]
Thanks for thinking this through with me, folks. Looking forward to the updated PR.

**Comment by submitnine** [comment]
I updated the PR, could you recheck if everything is fine? I couldn't test it on windows because I haven't setup a proper windows deploying machine. But I'm sure that the creator of the issue here need to update the ruby version to 2.3.0 or better :)

**Comment by sandeepnagra** [comment]
@samnissen - I ran the rspec tests but due to some weird issues in my local, I am seeing weird results and some tests are failing intermittently. Can you run he tests, up the version and publish the gem?

I will try to solve my local issues over the weekend and can give it a try again.

**Comment by Zejnilovic** [comment]
@samnissen I am sorry I didn't have time to take part in the collaboration. But I think locking the version is the best option. Using old ruby may be dangerous and is a way I never support. Every project should have an update strategy and if they don't, this is a reason to create one.

Lock the version.
Thank you all for your work.

**Comment by samnissen** [comment]
Closing this as complete, per the associated PR
